### ISSUE TITLE
Server JAR file check is in wrong location

### ISSUE THREAD

**Issue by joezimjs** [PrismarineJS/node-minecraft-wrap#20]
In `lib/wrap_server.js` on line 95, it checks to see if the server JAR file exists, but it is checking in the directory that this Node application is running from. On line 109, you set the CWD to the directory where the rest of the server files are, so it needs the JAR file to be there. The check on line 95 should check to see if it exists in that directory instead.

**Comment by rom1504** [comment]
MC_SERVER_JAR should be a full path.
