### ISSUE TITLE
Starting The Server

### ISSUE THREAD

**Issue by spiderlord202** [PrismarineJS/node-minecraft-wrap#48]
Hi. What is the "MC_SERVER_JAR" in  `new WrapServer(MC_SERVER_JAR,MC_SERVER_PATH[,OPTIONS])`. I tried the path of the of the .jar file but it does not work. I also tried requiring the jar file but that also does not work. The error is: 
`/home/container/node_modules/minecraft-wrap/lib/wrap_server.js:80                                                   `
 `Object.keys(propOverrides).forEach(prop => { props[prop] = propOverrides[prop] })                            `
`           ^                                                                                                                                                      `
`TypeError: Cannot convert undefined or null to object                                                                              `
` at Function.keys (<anonymous>)                                                                                                               `
`    at WrapServer.startServer (/home/container/node_modules/minecraft-wrap/lib/wrap_server.js:80:12)`
`    at Object.<anonymous> (/home/container/server.js:56:8)                                                                      `
So I am assuming it is an json object but where do you get it?

**Comment by u9g** [comment]
https://github.com/PrismarineJS/node-minecraft-wrap/blob/4e4177fdd4cac3d12d66ae7faa61a8f5baaa8822/examples/exampleWrapServer.js
