### ISSUE TITLE
Downloading versions pre-1.2.5?

### ISSUE THREAD

**Issue by deathcap** [PrismarineJS/node-minecraft-wrap#9]
tmp $ downloadMinecraft 1.2.4
[Error: download failed : server responds with status 403]

is the error I get when I try to download anything before 1.2.5. 

http://minecraft.gamepedia.com/Version_history

1.2.4, 1.2.3, 1.2.2, 1.2.1, 1.1, 1.0.1, 1.0.0, 1.0 also cannot download. Appears that 1.2.5 is the earlier version available through their AmazonAWS download site, so maybe not much node-minecraft-wrap can do here, short of some kind of patching service ala MCNostalgia. Curious how the official Minecraft launcher does it..

**Comment by rom1504** [comment]
The launcher only gets the client. Not sure if these old vanilla servers
are available on any mojang site.

We had to get the classic vanilla server from some random link on the
internet, when we worked on
https://github.com/mhsjlw/minecraft-classic-protocol (and the classic
client from the launcher doesn't have multiplayer functionality, had to use
classicube )

**Comment by rom1504** [comment]
https://launchermeta.mojang.com/mc/game/a4d513044d26ee59ce948263f1076dfe31136c8c/1.2.4.json only the client is available, not the server.

**Comment by rom1504** [comment]
So.
AFAIK these server jars aren't available anywhere so this isn't possible.
Let's close this.

Can be reopened if there is any way to do it.
